// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fs.proto

#ifndef PROTOBUF_proto_2ffs_2eproto__INCLUDED
#define PROTOBUF_proto_2ffs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)

namespace mypackage {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2ffs_2eproto();
void protobuf_AssignDesc_proto_2ffs_2eproto();
void protobuf_ShutdownFile_proto_2ffs_2eproto();

class Directory;
class File;

// ===================================================================

class File : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mypackage.File) */ {
 public:
  File();
  virtual ~File();

  File(const File& from);

  inline File& operator=(const File& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const File& default_instance();

  void Swap(File* other);

  // implements Message ----------------------------------------------

  inline File* New() const { return New(NULL); }

  File* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const File& from);
  void MergeFrom(const File& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(File* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string data_filename = 2;
  void clear_data_filename();
  static const int kDataFilenameFieldNumber = 2;
  const ::std::string& data_filename() const;
  void set_data_filename(const ::std::string& value);
  void set_data_filename(const char* value);
  void set_data_filename(const char* value, size_t size);
  ::std::string* mutable_data_filename();
  ::std::string* release_data_filename();
  void set_allocated_data_filename(::std::string* data_filename);

  // @@protoc_insertion_point(class_scope:mypackage.File)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr data_filename_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2ffs_2eproto();
  friend void protobuf_AssignDesc_proto_2ffs_2eproto();
  friend void protobuf_ShutdownFile_proto_2ffs_2eproto();

  void InitAsDefaultInstance();
  static File* default_instance_;
};
// -------------------------------------------------------------------

class Directory : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mypackage.Directory) */ {
 public:
  Directory();
  virtual ~Directory();

  Directory(const Directory& from);

  inline Directory& operator=(const Directory& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Directory& default_instance();

  void Swap(Directory* other);

  // implements Message ----------------------------------------------

  inline Directory* New() const { return New(NULL); }

  Directory* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Directory& from);
  void MergeFrom(const Directory& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Directory* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // repeated .mypackage.Directory directory = 2;
  int directory_size() const;
  void clear_directory();
  static const int kDirectoryFieldNumber = 2;
  const ::mypackage::Directory& directory(int index) const;
  ::mypackage::Directory* mutable_directory(int index);
  ::mypackage::Directory* add_directory();
  ::google::protobuf::RepeatedPtrField< ::mypackage::Directory >*
      mutable_directory();
  const ::google::protobuf::RepeatedPtrField< ::mypackage::Directory >&
      directory() const;

  // repeated .mypackage.File file = 3;
  int file_size() const;
  void clear_file();
  static const int kFileFieldNumber = 3;
  const ::mypackage::File& file(int index) const;
  ::mypackage::File* mutable_file(int index);
  ::mypackage::File* add_file();
  ::google::protobuf::RepeatedPtrField< ::mypackage::File >*
      mutable_file();
  const ::google::protobuf::RepeatedPtrField< ::mypackage::File >&
      file() const;

  // @@protoc_insertion_point(class_scope:mypackage.Directory)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::RepeatedPtrField< ::mypackage::Directory > directory_;
  ::google::protobuf::RepeatedPtrField< ::mypackage::File > file_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2ffs_2eproto();
  friend void protobuf_AssignDesc_proto_2ffs_2eproto();
  friend void protobuf_ShutdownFile_proto_2ffs_2eproto();

  void InitAsDefaultInstance();
  static Directory* default_instance_;
};
// ===================================================================

static const int kSerializeToOstreamFieldNumber = 60000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  serialize_to_ostream;

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// File

// optional string name = 1;
inline void File::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& File::name() const {
  // @@protoc_insertion_point(field_get:mypackage.File.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void File::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mypackage.File.name)
}
inline void File::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mypackage.File.name)
}
inline void File::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mypackage.File.name)
}
inline ::std::string* File::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mypackage.File.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* File::release_name() {
  // @@protoc_insertion_point(field_release:mypackage.File.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void File::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mypackage.File.name)
}

// optional string data_filename = 2;
inline void File::clear_data_filename() {
  data_filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& File::data_filename() const {
  // @@protoc_insertion_point(field_get:mypackage.File.data_filename)
  return data_filename_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void File::set_data_filename(const ::std::string& value) {
  
  data_filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mypackage.File.data_filename)
}
inline void File::set_data_filename(const char* value) {
  
  data_filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mypackage.File.data_filename)
}
inline void File::set_data_filename(const char* value, size_t size) {
  
  data_filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mypackage.File.data_filename)
}
inline ::std::string* File::mutable_data_filename() {
  
  // @@protoc_insertion_point(field_mutable:mypackage.File.data_filename)
  return data_filename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* File::release_data_filename() {
  // @@protoc_insertion_point(field_release:mypackage.File.data_filename)
  
  return data_filename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void File::set_allocated_data_filename(::std::string* data_filename) {
  if (data_filename != NULL) {
    
  } else {
    
  }
  data_filename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data_filename);
  // @@protoc_insertion_point(field_set_allocated:mypackage.File.data_filename)
}

// -------------------------------------------------------------------

// Directory

// optional string name = 1;
inline void Directory::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Directory::name() const {
  // @@protoc_insertion_point(field_get:mypackage.Directory.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Directory::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mypackage.Directory.name)
}
inline void Directory::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mypackage.Directory.name)
}
inline void Directory::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mypackage.Directory.name)
}
inline ::std::string* Directory::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mypackage.Directory.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Directory::release_name() {
  // @@protoc_insertion_point(field_release:mypackage.Directory.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Directory::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mypackage.Directory.name)
}

// repeated .mypackage.Directory directory = 2;
inline int Directory::directory_size() const {
  return directory_.size();
}
inline void Directory::clear_directory() {
  directory_.Clear();
}
inline const ::mypackage::Directory& Directory::directory(int index) const {
  // @@protoc_insertion_point(field_get:mypackage.Directory.directory)
  return directory_.Get(index);
}
inline ::mypackage::Directory* Directory::mutable_directory(int index) {
  // @@protoc_insertion_point(field_mutable:mypackage.Directory.directory)
  return directory_.Mutable(index);
}
inline ::mypackage::Directory* Directory::add_directory() {
  // @@protoc_insertion_point(field_add:mypackage.Directory.directory)
  return directory_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::mypackage::Directory >*
Directory::mutable_directory() {
  // @@protoc_insertion_point(field_mutable_list:mypackage.Directory.directory)
  return &directory_;
}
inline const ::google::protobuf::RepeatedPtrField< ::mypackage::Directory >&
Directory::directory() const {
  // @@protoc_insertion_point(field_list:mypackage.Directory.directory)
  return directory_;
}

// repeated .mypackage.File file = 3;
inline int Directory::file_size() const {
  return file_.size();
}
inline void Directory::clear_file() {
  file_.Clear();
}
inline const ::mypackage::File& Directory::file(int index) const {
  // @@protoc_insertion_point(field_get:mypackage.Directory.file)
  return file_.Get(index);
}
inline ::mypackage::File* Directory::mutable_file(int index) {
  // @@protoc_insertion_point(field_mutable:mypackage.Directory.file)
  return file_.Mutable(index);
}
inline ::mypackage::File* Directory::add_file() {
  // @@protoc_insertion_point(field_add:mypackage.Directory.file)
  return file_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::mypackage::File >*
Directory::mutable_file() {
  // @@protoc_insertion_point(field_mutable_list:mypackage.Directory.file)
  return &file_;
}
inline const ::google::protobuf::RepeatedPtrField< ::mypackage::File >&
Directory::file() const {
  // @@protoc_insertion_point(field_list:mypackage.Directory.file)
  return file_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mypackage

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2ffs_2eproto__INCLUDED
